### ISSUE TITLE
Question about showModal/onShow parameters

### ISSUE THREAD

**Issue by netfalo** [ghosh/Micromodal#259] opened 2019-11-26 08:57 UTC
Hi,

Is the click event intentionally not used in the showModal?

In the registerTriggers it is passed in, but it is not used in the showModal
registerTriggers:
`trigger.addEventListener('click', event => this.showModal(event))`
showModal:
`showModal () {`

It would be useful to know the triggering click event in the config.onShow.

In my usecase I need to modify the modal content during onShow.

BR
/Marci

**Comment by ghosh** [comment] 2020-03-24 01:54
Duplicate of #130

**Closed by ghosh** 2020-03-24 01:54 UTC
