### ISSUE TITLE
Problems when trying to open/close programmatically

### ISSUE THREAD

**Issue by kbudasov** [ghosh/Micromodal#196] opened 2019-05-31 07:52 UTC
When having only modal ID (without element with `data-trigger-attrribute`), modal callback doesn't work
(triggered `MicroModal.show('modal-id'); // [1]`)
Also, unable to close modal by triggering
`MicroModal.close('modal-id'); // [2]`

**Comment by kbudasov** [comment] 2019-05-31 08:39
To clarify the situation: yes, I can use "custom" callbacks; but still unable to extend standard config (provided in Global Init function)

**Comment by mrmathewc** [comment] 2019-07-11 20:37
Also had issues with this. A workaround was I added an ID to the close trigger, then just executed `$('#modal-close').click();` where necessary, in my case was on Ajax success.

**Comment by ghosh** [comment] 2019-07-21 12:32
Closing as duplicate of #197. Will be fixed in next release.

**Closed by ghosh** 2019-07-21 12:32 UTC

**Comment by cnobile2012** [comment] 2020-01-20 23:13
I'm having the same close issue. I haven't tried the issue with a callback.
