### ISSUE TITLE
Modals opened by script cause error because of a non-existant `event`

### ISSUE THREAD

**Issue by ignazkevenaar** [ghosh/Micromodal#221] opened 2019-07-25 11:10 UTC
Modals opened by script cause error because of a non-existant `event` in the `showModal` function.
The function is called without arguments in the `show`-function.

Could it be as easy as just checking for `undefined`?

**Comment by ghosh** [comment] 2019-09-05 03:57
This error was being caused by another piece of code which has been fixed now.

**Closed by ghosh** 2019-09-05 03:57 UTC
